"""
TrafficEnv: Multi-Agent Traffic Signal Control Environment with Dynamic Structural Parsing.

This environment implements the MARL_SGAT framework for traffic signal control using SUMO.
It features a custom reward function based on the paper's 'Heterogeneous Correlation Index',
which accounts for the structural relationships between upstream and downstream intersections.

KEY FEATURES:
- DYNAMIC PARSING: Uses sumolib to read 'network.net.xml' to extract real-world lane counts (m_p)
  and edge lengths (dist) for accurate heterogeneous correlation calculations.
- ACTION SPACE (Phase Duration Adjustment): Allows agents to extend or reduce green phase 
  durations by delta_t_tilde (4s) at specific reassessment intervals (12s).
- REWARD LOGIC: Implements Equation (8) using calculated cor_forward and cor_backward indices
  to scale the local average delay based on intersection scale and proximity.
"""
from pettingzoo import ParallelEnv
import traci
import traci.connection
import sumolib
import numpy as np
from env.observation import MARLObservation

class TrafficEnv(ParallelEnv):
    metadata = {"name": "traffic_marl_env"}

    def __init__(self, net_file="/content/MARL-TSC-SUMO-Group/sumo/network.net.xml"):
        """
        Initializes the environment and parses the SUMO network to ground the agent logic
        in the actual physical topology of the grid.
        
        Args:
            net_file (str): Path to the SUMO .net.xml file used to extract structural metadata.
        """
        # List of all 25 traffic light IDs generated by netgenerate for the 5x5 grid.
        self.sumo_ids = ['A1', 'A2', 'A3', 'B0', 'B1', 'B2', 'B3', 'B4', 'C0', 'C1', 'C2', 'C3', 'C4', 'D0', 'D1', 'D2', 'D3', 'D4', 'E1', 'E2', 'E3']
        self.agents = [f"agent_{i}" for i in range(len(self.sumo_ids))]
        self.agent_to_sumo = {f"agent_{i}": sid for i, sid in enumerate(self.sumo_ids)}
        
        # --- MARL SGAT HYPERPARAMETERS (Section 4.1) ---
        self.q_scaling = 3.0           # Scaling factor 'q' used to unify numerical ranges.
        self.min_green = 10            # Minimum safety duration for a green phase.
        self.max_green = 60            # Maximum allowed green duration.
        self.delta_t_tilde = 4         # Green light adjustment time (delta_t_tilde) = 4s.
        self.reassessment_interval = 12 # Time interval between two consecutive actions (delta_t) = 12s.

        # --- DYNAMIC NETWORK ANALYSIS ---
        # Load the network structure using sumolib to replace static placeholders.
        # This extracts 'm_p' (lane count) and 'dist' (x_p) for Heterogeneity formulas.
        self.net = sumolib.net.readNet(net_file)
        self.structural_data = self._parse_network_structure()

        # State tracking buffers for timing and reward calculations.
        self.last_waiting_times = {agent: 0 for agent in self.agents}
        self.current_phase_timer = {agent: 0 for agent in self.agents}
        self.observations_manager = {}

    def _parse_network_structure(self):
        """
        Iterates through the SUMO network nodes to extract topological data used in
        the Heterogeneous Correlation Index formulas (Equations 6 & 7).
        """
        data = {}
        for agent in self.agents:
            sumo_id = self.agent_to_sumo[agent]
            node = self.net.getNode(sumo_id)
            
            # Extract 'm_p_i': Total number of incoming lanes at this intersection node.
            m_p_i = sum([edge.getLaneNumber() for edge in node.getIncoming()])
            
            # Extract 'dist' (x_p): Length of the primary incoming edge.
            # This represents the physical distance over which correlations act.
            dist = 500.0
            incoming_edges = node.getIncoming()
            if incoming_edges:
                dist = incoming_edges[0].getLength()

            data[agent] = {
                'm_p': max(1, m_p_i),
                'dist': max(1.0, dist)
            }
        return data

    def reset(self, seed=None, options=None):
        """
        Resets the simulation and re-initializes TraCI-dependent objects.
        """
        try:
            import traci.connection
            if 'default' in traci.connection._connections: traci.close()
        except: pass

        traci.start(["sumo", "-c", "/content/MARL-TSC-SUMO-Group/sumo/config.sumocfg"])
        
        # Managers must be reset after traci.start() to access live simulation state.
        self.observations_manager = {agent: MARLObservation(self.agent_to_sumo[agent]) for agent in self.agents}
        self.last_waiting_times = {agent: 0 for agent in self.agents}
        self.current_phase_timer = {agent: 0 for agent in self.agents}
        return {agent: self.observations_manager[agent].get() for agent in self.agents}

    def step(self, actions):
        """
        Executes the provided actions and advances the world state by 12 seconds.
        Handles automatic transitions to yellow phases if durations are exceeded.
        """
        # 1. Apply adjustments from the agents (delta_t_tilde = 4s)
        for agent, action in actions.items():
            self._apply_action(agent, action)
        
        # 2. Advance simulation by reassessment_interval (12 seconds)
        # During this loop, the environment manages sub-second logic and phase cycles.
        for _ in range(self.reassessment_interval):
            traci.simulationStep()
            for agent in self.agents: 
                self.current_phase_timer[agent] += 1
                # Transition logic: If the timer hits the phase duration, move to the next phase index.
                sumo_id = self.agent_to_sumo[agent]
                if self.current_phase_timer[agent] >= traci.trafficlight.getPhaseDuration(sumo_id):
                    curr_phase = traci.trafficlight.getPhase(sumo_id)
                    traci.trafficlight.setPhase(sumo_id, (curr_phase + 1) % 4)
                    self.current_phase_timer[agent] = 0

        # 3. Aggregate observations and compute SGAT rewards for the 12s interval
        obs = {agent: self.observations_manager[agent].get() for agent in self.agents}
        rewards = {agent: self._compute_reward(agent) for agent in self.agents}
        return obs, rewards, {a: False for a in self.agents}, {a: False for a in self.agents}, {a: {} for a in self.agents}

    def _get_hetero_index(self, agent):
        """
        Calculates the directional correlation indices (cor_forward and cor_backward)
        using the dynamic structural data (Eq 6 & 7).
        """
        m_p_i = self.structural_data[agent]['m_p']
        dist = self.structural_data[agent]['dist']
        
        # Equation 6/7: cor = m_neighbor / (m_current * q * sqrt(distance))
        # We assume neighbors share structural characteristics in this configuration.
        cor_forward = m_p_i / (m_p_i * self.q_scaling * np.sqrt(dist))
        cor_backward = m_p_i / (m_p_i * self.q_scaling * np.sqrt(dist))
        return cor_forward, cor_backward

    def _compute_reward(self, agent):
        """
        Implements Equation (8) for Heterogeneous Reward Calculation.
        Weights local delay feedback by the spatiotemporal correlation indices.
        """
        sumo_id = self.agent_to_sumo[agent]
        lanes = traci.trafficlight.getControlledLanes(sumo_id)
        
        # Calculate local average delay (change in waiting time)
        current_waiting_time = sum([traci.lane.getWaitingTime(l) for l in lanes])
        delay = (self.last_waiting_times[agent] - current_waiting_time) / 100.0
        
        # Apply Heterogeneity scaling
        cor_f, cor_b = self._get_hetero_index(agent)
        
        # Final reward formulation: Volume Ratio * Cor_Forward * Cor_Backward * Delay
        reward = 1.0 * cor_f * cor_b * delay
        
        self.last_waiting_times[agent] = current_waiting_time
        return float(reward)

    def _apply_action(self, agent, action):
        """
        Translates RL agent decisions into green phase duration adjustments.
        Uses delta_t_tilde (4s) as the adjustment increment.
        """
        sumo_id = self.agent_to_sumo[agent]
        current_phase = traci.trafficlight.getPhase(sumo_id)
        
        # Paper logic: Only adjust during green phases (typically even indices)
        if current_phase % 2 != 0: return
        
        dur = traci.trafficlight.getPhaseDuration(sumo_id)
        # Action 1: Extend (+4s), Action 2: Reduce (-4s), Action 0: Maintain
        if action == 1: 
            traci.trafficlight.setPhaseDuration(sumo_id, min(self.max_green, dur + self.delta_t_tilde))
        elif action == 2: 
            traci.trafficlight.setPhaseDuration(sumo_id, max(self.min_green, dur - self.delta_t_tilde))
