"""
TrafficEnv: Updated with MARL SGAT Observation Space and Phase Duration Adjustment Action Space.

This environment implements a multi-agent traffic signal control simulation using SUMO,
wrapped with PettingZoo's ParallelEnv API. Each traffic light acts as an independent agent
making decisions to optimize traffic flow.

ACTION SPACE LOGIC (Phase Duration Adjustment):
- Action 0: Maintain current green time. The phase continues for its set duration.
- Action 1: Extend current green phase by delta_t (e.g., +5s). This allows more vehicles to clear.
- Action 2: Reduce current green phase by delta_t (e.g., -5s). This shortens the green phase,
potentially to switch to a more critical approach faster.

This version manages internal timers to ensure minimum/maximum green times and handles
transitions to yellow phases automatically, mimicking realistic traffic light operations.
"""
from pettingzoo import ParallelEnv
import traci
import traci.connection
import numpy as np
from env.observation import MARLObservation # Import the detailed observation class

class TrafficEnv(ParallelEnv):
    metadata = {"name": "traffic_marl_env"}

    def __init__(self):
        """
        Initializes the TrafficEnv, setting up agent IDs, SUMO parameters, and internal state.
        """
        # List of SUMO traffic light IDs that are agents in this environment.
        # These IDs are typically derived from the `network.net.xml` file generated by netgenerate.
        self.sumo_ids = ['A1', 'B0', 'B1', 'B2', 'C1'] # Example IDs from a 3x3 grid
        # PettingZoo agent IDs, mapping to the SUMO IDs.
        self.agents = [f"agent_{i}" for i in range(len(self.sumo_ids))]
        # Bidirectional mapping for easy conversion between PettingZoo agent ID and SUMO traffic light ID.
        self.agent_to_sumo = {f"agent_{i}": sid for i, sid in enumerate(self.sumo_ids)}
        self.sumo_to_agent = {sid: f"agent_{i}" for i, sid in enumerate(self.sumo_ids)}

        # Simulation constants for phase duration adjustment.
        self.min_green = 10 # Minimum green light duration in seconds.
        self.max_green = 60 # Maximum green light duration in seconds.
        self.delta_t = 5    # The amount of time (in seconds) to extend or reduce a green phase.

        # Internal state tracking for reward calculation and phase management.
        # Tracks the last observed waiting time for each agent's controlled lanes.
        self.last_waiting_times = {agent: 0 for agent in self.agents}
        # Tracks how long the current phase has been active for each traffic light.
        self.current_phase_timer = {agent: 0 for agent in self.agents}
        # Tracks if a traffic light is currently in a yellow phase.
        self.is_yellow = {agent: False for agent in self.agents}

        # Initialize observation objects for each agent. These objects will handle state extraction.
        self.observations_manager = {agent: MARLObservation(self.agent_to_sumo[agent]) for agent in self.agents}


    def reset(self, seed=None, options=None):
        """
        Resets the SUMO simulation and initializes all internal state variables for a new episode.

        Args:
            seed (int, optional): Seed for random number generation (not fully implemented in SUMO for reproducibility).
            options (dict, optional): Additional options for the environment reset.

        Returns:
            dict: A dictionary mapping agent IDs to their initial observation vectors.
        """
        # Close any existing TraCI connection to ensure a clean restart.
        try:
            if "default" in traci.connection._connections: traci.close()
        except Exception: # Catch potential errors if connection is already closed or non-existent
            pass
        finally:
            # Ensure the connection is fully cleared from TraCI's internal state
            if "default" in traci.connection._connections: del traci.connection._connections["default"]

        # Start a new SUMO simulation instance. The config.sumocfg specifies the network and routes.
        traci.start(["sumo", "-c", "/content/MARL-TSC-SUMO-Group/sumo/config.sumocfg"])

        # Reset internal state trackers for the new episode.
        self.last_waiting_times = {agent: 0 for agent in self.agents}
        self.current_phase_timer = {agent: 0 for agent in self.agents}
        self.is_yellow = {agent: False for agent in self.agents}

        # Get and return initial observations for all agents.
        return {agent: self.observations_manager[agent].get() for agent in self.agents}

    def step(self, actions):
        """
        Applies the chosen actions for all agents, steps the SUMO simulation, and computes
        new observations, rewards, and episode termination/truncation statuses.

        Args:
            actions (dict): A dictionary mapping agent IDs to their chosen actions (0, 1, or 2).

        Returns:
            tuple: (observations, rewards, terminations, truncations, infos)
                - observations (dict): New observation vectors for all agents.
                - rewards (dict): Reward for each agent for the current step.
                - terminations (dict): Boolean indicating if an agent's episode has terminated.
                - truncations (dict): Boolean indicating if an agent's episode has been truncated.
                - infos (dict): Additional information (empty in this basic implementation).
        """
        # Apply actions for each agent. This involves potentially adjusting green phase durations.
        for agent, action in actions.items():
            self._apply_action(agent, action)

        # Advance the SUMO simulation by one step (typically 1 second).
        traci.simulationStep()

        # Increment the internal phase timer for each agent.
        for agent in self.agents:
            self.current_phase_timer[agent] += 1

        # Get updated observations and compute rewards for all agents.
        observations = {agent: self.observations_manager[agent].get() for agent in self.agents}
        rewards = {agent: self._compute_reward(agent) for agent in self.agents}

        # By default, episodes do not terminate or truncate based on agent actions in this setup.
        # Termination and truncation logic would typically depend on specific simulation goals (e.g., max steps).
        return observations, rewards, {a: False for a in self.agents}, {a: False for a in self.agents}, {a: {} for a in self.agents}

    def _apply_action(self, agent, action):
        """
        Applies the chosen action to the specified traffic light in SUMO.
        This involves adjusting green phase durations and handling phase transitions (including yellow phases).

        Args:
            agent (str): The ID of the agent taking the action.
            action (int): The chosen action (0: Maintain, 1: Extend, 2: Reduce).
        """
        sumo_id = self.agent_to_sumo[agent]
        current_phase = traci.trafficlight.getPhase(sumo_id) # Current phase index of the traffic light.

        # SUMO traffic lights often use an even-odd scheme for phases:
        # Even indices (0, 2, ...) are typically green phases.
        # Odd indices (1, 3, ...) are typically yellow (or inter-green) phases.

        # If the traffic light is currently in a yellow phase (odd index),
        # it should simply wait for the yellow phase to complete its fixed duration.
        if current_phase % 2 != 0: # Check if it's an odd-indexed phase (yellow)
            if self.current_phase_timer[agent] >= 3: # Assuming a fixed 3-second yellow phase duration.
                traci.trafficlight.setPhase(sumo_id, (current_phase + 1) % 4) # Move to the next phase (green).
                self.current_phase_timer[agent] = 0 # Reset timer for the new phase.
            return # No action modification during yellow phase.

        # --- Green Phase Action Logic (only applies if not in a yellow phase) ---

        # Get the current duration of the active green phase.
        current_phase_duration = traci.trafficlight.getPhaseDuration(sumo_id)
        new_duration = current_phase_duration # Initialize new_duration with current duration.

        if action == 1: # Action 1: Extend current green phase
            # Increase duration by delta_t, but don't exceed max_green.
            new_duration = min(self.max_green, current_phase_duration + self.delta_t)
        elif action == 2: # Action 2: Reduce current green phase
            # Decrease duration by delta_t, but don't go below min_green.
            new_duration = max(self.min_green, current_phase_duration - self.delta_t)
        # Action 0 (Maintain) means new_duration remains current_phase_duration.

        # Apply the potentially adjusted duration to the SUMO traffic light.
        traci.trafficlight.setPhaseDuration(sumo_id, new_duration)

        # Check if the current green phase has expired based on its (potentially new) duration.
        if self.current_phase_timer[agent] >= new_duration: # Note: Using new_duration here is crucial.
            # If expired, transition to the next phase (which would be a yellow phase).
            traci.trafficlight.setPhase(sumo_id, (current_phase + 1) % 4) # Cycle to the next phase.
            self.current_phase_timer[agent] = 0 # Reset timer for the new phase.

    def _compute_reward(self, agent):
        """
        Calculates the reward for a given agent based on changes in waiting time and throughput.
        This reward function encourages actions that reduce delay and increase vehicle flow.

        Args:
            agent (str): The ID of the agent for which to compute the reward.

        Returns:
            float: The calculated reward for the agent.
        """
        sumo_id = self.agent_to_sumo[agent]
        lanes = traci.trafficlight.getControlledLanes(sumo_id) # Get all lanes controlled by this traffic light.

        # Waiting Time Component:
        # `traci.lane.getWaitingTime(l)` returns the waiting time of vehicles on lane `l` in the last step.
        # A reduction in total waiting time across controlled lanes leads to a positive reward.
        current_waiting_time = sum([traci.lane.getWaitingTime(l) for l in lanes])
        delay_component = (self.last_waiting_times[agent] - current_waiting_time) / 100.0
        # Dividing by 100.0 to scale the reward component, as raw waiting times can be large.

        # Throughput Component:
        # `traci.lane.getLastStepVehicleNumber(l)` returns the number of vehicles that passed over lane `l`
        # during the last simulation step (i.e., throughput).
        # Higher throughput contributes positively to the reward, encouraging efficient movement.
        throughput = sum([traci.lane.getLastStepVehicleNumber(l) for l in lanes])
        throughput_component = throughput * 0.1
        # Multiplying by 0.1 to weigh the throughput component relative to the delay component.

        # Total Reward: Combination of reduced delay and increased throughput.
        reward = delay_component + throughput_component

        # Update the last waiting time for the next step's reward calculation.
        self.last_waiting_times[agent] = current_waiting_time

        return float(reward)
